name: Test, Build & Publish

on:
  create:
    tags: 'v*'
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: npm install, build
      run: |
        npm install
      env:
        CI: true
    - name: Run test
      run: ./node_modules/.bin/ember build
  deploy:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: deploy npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish || echo "already published"
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
